[workspace]
resolver = "2"
members = [
  "crates/*",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
haste = { git = "https://github.com/blukai/haste.git", rev = "0b620718095c22206b0f3ad51cf63109005fc425", features = ["preserve-metadata"] }
wasm-bindgen = "0.2"

