[package]
name = "haste"
version = "0.0.0"
edition = "2021"

[dependencies]
haste = { git = "https://github.com/blukai/haste.git", rev = "0fa015ddf428468abfda843fced68557533f5694", package = "haste", features = ["preserve-metadata"] }
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
path = "src/lib/haste/haste.rs"
