[workspace]
resolver = "2"
members = [
  "crates/*",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
haste = { git = "https://github.com/blukai/haste.git", rev = "4c9a560", features = ["preserve-metadata"] }
wasm-bindgen = "0.2"

