[workspace]
resolver = "2"
members = [
  "crates/*",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
haste = { git = "https://github.com/blukai/haste.git", rev = "84507a99a46ffb1b8dcc1a97c70842e2bc5274ad", features = ["preserve-metadata"] }
wasm-bindgen = "0.2"

