[package]
name = "haste"
version = "0.0.0"
edition = "2021"

[dependencies]
haste = { git = "https://github.com/blukai/haste.git", rev = "fbda4a3ec4727687e7097a69bebda9740469fa5a", package = "haste", features = ["preserve-metadata"] }
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
path = "src/lib/haste/haste.rs"
