[package]
name = "haste-wasm"
version = "0.0.0"
edition = "2021"

[dependencies]
haste.workspace = true
wasm-bindgen.workspace = true

[features]
protobuf-src = ["haste/protobuf-src"]

[lib]
crate-type = ["cdylib"]
